Repository PKUHPC/CraneSched-FrontEnd, pull requests merged in 2024-11, with the labels that each got.

#187 fix: calloc cbatch crun arg check
  etc/cplugind.service
  internal/calloc/calloc.go
  internal/cbatch/cbatch.go
  internal/crun/crun.go
  internal/util/string.go
Labels: refactor

#178 Separate Authentication and Modification in AccountManager
  internal/cacctmgr/CmdArgParser.go
  internal/cacctmgr/cacctmgr.go
  internal/util/err.go
  internal/util/string.go
  protos/Crane.proto
  protos/PublicDefs.proto
Labels: refactor

#207 feat: Add cbatch --wrap "Command"
  internal/cbatch/CmdArgParser.go
Labels: enhancement

#210 fix: query, block errmsg
  internal/cacctmgr/cacctmgr.go
Labels: bug

#208 Allow specifying time with now or now+-duration
  internal/util/string.go
Labels: enhancement
