Repository PKUHPC/CraneSched-FrontEnd, pull requests merged in 2024-12, with the labels that each got.

#214 feat: Add command `ceff` for performance info display
  cmd/ceff/ceff.go
  internal/ceff/CmdArgPaser.go
  internal/ceff/ceff.go
  internal/cplugind/loader.go
  internal/util/grpc.go
  internal/util/string.go
  internal/util/util.go
Labels: enhancement

#209 feat: version show CraneSched v1.0.0 release
  internal/util/version.go
Labels: refactor

#219 Bugfix: Check permission when update node
  internal/ccontrol/ccontrol.go
  protos/Crane.proto
Labels: bug

#211 Added energy consumption collection plug-in
  Makefile
  api/plugin.go
  go.mod
  go.sum
  internal/cplugind/cplugind.go
  internal/cplugind/loader.go
  internal/cplugind/server.go
  plugin/dummy/dummy.go
  plugin/energy/energy.go
  plugin/energy/energy.yaml
  plugin/energy/pkg/cgroup/interface.go
  plugin/energy/pkg/cgroup/v1.go
  plugin/energy/pkg/config/config.go
  plugin/energy/pkg/db/factory.go
  plugin/energy/pkg/db/influxdb.go
  plugin/energy/pkg/db/interface.go
  plugin/energy/pkg/gpu/interface.go
  plugin/energy/pkg/gpu/nvml.go
  plugin/energy/pkg/gpu/nvml_stub.go
  plugin/energy/pkg/gpu/reader.go
  plugin/energy/pkg/ipmi/reader.go
  plugin/energy/pkg/monitor/monitor.go
  plugin/energy/pkg/monitor/node.go
  plugin/energy/pkg/monitor/subscriber.go
  plugin/energy/pkg/monitor/task.go
  plugin/energy/pkg/rapl/reader.go
  plugin/energy/pkg/sysload/reader.go
  plugin/energy/pkg/types/types.go
  plugin/mail/mail.go
  plugin/monitor/monitor.go
  protos/Plugin.proto
Labels: enhancement
